module Loader
  LOCAL_BIN = 'bin/mrsk'

  def load_local_bin
    original_cwd = Dir.pwd

    loop do
      if bin_exists?
        exec LOCAL_BIN, *ARGV
      end

      # If we exhaust the search there is no executable, run bundled mrsk from original cwd
      Dir.chdir(original_cwd) && return if Pathname.new(Dir.pwd).root?

      # Otherwise keep moving upwards in search of an executable.
      Dir.chdir("..")
    end
  end

  private

  def bin_exists?
    return unless File.exist?(LOCAL_BIN) || File.executable?(LOCAL_BIN)
    return unless File.read(LOCAL_BIN, 300).include?("This file was generated by Bundler")

    true
  end
end
